server.port=8081

spring.datasource.url=jdbc:h2:file:C:/Users/minki/mapledb;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

nexon.api.base-url=https://open.api.nexon.com/maplestorym/v1

spring.profiles.include=secret