# [Server & Common]
server.port=8081
nexon.api.base-url=https://open.api.nexon.com/maplestorym/v1
spring.config.import=optional:classpath:application-secret.properties

# 외부 접근 가능한 서버 주소 (카카오톡 링크 미리보기용)
bot.public-base-url=https://maplebot-huqv.onrender.com
