# [Server & Common]
server.port=8081
nexon.api.base-url=https://open.api.nexon.com/maplestorym/v1
spring.config.import=optional:classpath:application-secret.properties

# [Prod DB 환경 - PostgreSQL]
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://${DB_HOST:bot-db}:5432/${DB_NAME:bot_db}
spring.datasource.username=${DB_USERNAME:bot_user}
spring.datasource.password=${DB_PASSWORD:bot_password}

# [Prod JPA 안전 설정]
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect